config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :animes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
end

app/models/anime.rb
class Anime < ApplicationRecord
    validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true
                     
    validates :body, presence: true,
                     length: {minimum: 5}             
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true
    validates :body, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
    before_action :set_anime, only: %i[ show edit update destroy ]

    def index
        @animes = Anime.all
    end

    def show
    end

    def new
        @anime = Anime.new
    end

    def edit
    end

    def create
        @anime = Anime.new(anime_params)

        respond_to do |format|
            if @anime.save
                format.html { redirect_to anime_url(@anime), notice: "Anime was successfully created." }
                format.json { render :show, status: :created, location: @anime }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @anime.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @anime.update(anime_params)
                format.html { redirect_to anime_url(@anime), notice: "Anime was successfully updated." }
                format.json { render :show, status: :ok, location: @anime }
              else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @anime.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @anime.destroy!
    
        respond_to do |format|
          format.html { redirect_to animes_url, notice: "Anime was successfully destroyed." }
          format.json { head :no_content }
        end
      end

    private
      def set_anime
        @anime = Anime.find(params[:id])
      end
  
      def anime_params
        params.require(:anime).permit(:title, :main_character, :year_created, :synopsis)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
    # list all articles
    @articles = Article.all
    end
    
    def new
    # display a form where you can add an article
    @article = Article.new
    end
    
    def create 
    # create article (thru model/activerecord)
        @article = Article.new
        @article.name = params[:name]
        @article.body = params[:body]
s
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
    # display a form where you can edit an article
    end

    def updated 
    # update article (thru model/activerecord)
    end 

    def delete 
    # delete article (thru model/activerecord)
    end

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy!

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :genre, :year_released, :publisher)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/animes/_anime.html.erb
<div id="<%= dom_id anime %>">
  <p>
    <strong>Title:</strong>
    <%= anime.title %>
  </p>

  <p>
    <strong>Main character:</strong>
    <%= anime.main_character %>
  </p>

  <p>
    <strong>Year created:</strong>
    <%= anime.year_created %>
  </p>
  
  <p>
    <strong>Synopsis:</strong>
    <%= anime.synopsis %>
  </p>

</div>

app/views/animes/_form.html.erb
<%= form_with(model: anime) do |form| %>
  <% if anime.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
        <% anime.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :main_character, style: "display: block" %>
    <%= form.text_field :main_character %>
  </div>

  <div>
    <%= form.label :year_created, style: "display: block" %>
    <%= form.number_field :year_created %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Show this anime", @anime %> |
  <%= link_to "Back to animes", animes_path %>
</div>

app/views/animes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Animes</h1>

<div id="animes">
  <% @animes.each do |anime| %>
    <%= render anime %>
    <p>
      <%= link_to "Show this anime", anime %>
    </p>
  <% end %>
</div>

<%= link_to "New anime", new_anime_path %>

app/views/animes/new.html.erb
<h1>New anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Back to animes", animes_path %>
</div>

app/views/animes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @anime %>

<div>
  <%= link_to "Edit this anime", edit_anime_path(@anime) %> |
  <%= link_to "Back to animes", animes_path %>

  <%= button_to "Destroy this anime", @anime, method: :delete %>
</div>

app/views/articles/index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
        <tr>
            <td> <%= article.id %> </td>
            <td> <%= article.name %> </td>
            <td> <%= article.body %> </td>
        </tr>
    <% end %>
    </tbody>
</table>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>

    <p>
        <% if @article.errors.any? %>
            <ul>
            <% @article.errors.full_messages.each do |message| %>
         <li><%= message %></li>
            <% end %>
            </ul>

        <% end %>
    </p>

    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :body %><br/>
        <%= f.text_field :body %>
    </p>

    <p>
    <%= f.submit %>
    </p>

    <% end %>

  

    

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :year_released, style: "display: block" %>
    <%= form.number_field :year_released %>
  </div>

  <div>
    <%= form.label :publisher, style: "display: block" %>
    <%= form.text_field :publisher %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Title:</strong>
    <%= game.title %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= game.genre %>
  </p>

  <p>
    <strong>Year released:</strong>
    <%= game.year_released %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= game.publisher %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>